version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/frankenphp.Dockerfile
    container_name: nuri-backend-app
    restart: unless-stopped
    volumes:
      - ./:/app
    depends_on:
      - mysql
    networks:
      - nuri-net
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: nuri_db
      DB_USERNAME: root
      DB_PASSWORD:

  mysql:
    image: mysql:8.0
    container_name: nuri-backend-mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: nuri_db
      MYSQL_USER: nuri
      MYSQL_PASSWORD:
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nuri-net
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nuri-backend-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD:
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - nuri-net

volumes:
  mysql_data:

networks:
  nuri-net:
    driver: bridge
